//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "ban")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub user_id: i32,
	pub created_at: i64,
	pub expires_at: Option<i64>,
	pub issuer: Option<i32>,
	#[sea_orm(column_type = "Text", nullable)]
	pub reason: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::Issuer",
		to = "super::user::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Issuer,
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::UserId",
		to = "super::user::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	User,
}

impl ActiveModelBehavior for ActiveModel {}
