//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (table_name = "board")] pub struct Model { # [sea_orm (primary_key)] # [serde (skip_deserializing)] pub id : i32 , # [sea_orm (column_type = "Text")] pub name : String , pub created_at : i64 , pub shape : Json , pub max_stacked : i32 , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (has_many = "super::board_sector::Entity")] BoardSector , # [sea_orm (has_many = "super::color::Entity")] Color , # [sea_orm (has_many = "super::placement::Entity")] Placement , }

impl Related < super :: board_sector :: Entity > for Entity { fn to () -> RelationDef { Relation :: BoardSector . def () } }

impl Related < super :: color :: Entity > for Entity { fn to () -> RelationDef { Relation :: Color . def () } }

impl Related < super :: placement :: Entity > for Entity { fn to () -> RelationDef { Relation :: Placement . def () } }

impl ActiveModelBehavior for ActiveModel { }