//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "report")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	#[sea_orm(primary_key, auto_increment = false)]
	pub revision: i32,
	pub closed: bool,
	pub reason: String,
	pub timestamp: i64,
	pub reporter: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::report_artifact::Entity")]
	ReportArtifact,
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::Reporter",
		to = "super::user::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	User,
}

impl Related<super::report_artifact::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ReportArtifact.def()
	}
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::User.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
