//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_id")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	#[sea_orm(unique)]
	pub uid: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::placement::Entity")]
	Placement,
	#[sea_orm(has_many = "super::report::Entity")]
	Report,
}

impl Related<super::placement::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Placement.def()
	}
}

impl Related<super::report::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Report.def()
	}
}

impl Related<super::report_artifact::Entity> for Entity {
	fn to() -> RelationDef {
		super::report::Relation::ReportArtifact.def()
	}
	fn via() -> Option<RelationDef> {
		Some(super::report::Relation::UserId.def().rev())
	}
}

impl ActiveModelBehavior for ActiveModel {}
