//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "board_notice")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub board: i32,
	pub title: String,
	pub content: String,
	pub created_at: i64,
	pub expires_at: Option<i64>,
	pub author: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::board::Entity",
		from = "Column::Board",
		to = "super::board::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Board,
}

impl Related<super::board::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Board.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
