//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "board")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	#[sea_orm(column_type = "Text")]
	pub name: String,
	pub created_at: i64,
	pub max_stacked: i32,
	#[sea_orm(column_type = "JsonBinary")]
	pub shape: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::board_sector::Entity")]
	BoardSector,
	#[sea_orm(has_many = "super::color::Entity")]
	Color,
	#[sea_orm(has_many = "super::placement::Entity")]
	Placement,
}

impl Related<super::board_sector::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::BoardSector.def()
	}
}

impl Related<super::color::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Color.def()
	}
}

impl Related<super::placement::Entity> for Entity {
	fn to() -> RelationDef {
		super::color::Relation::Placement.def()
	}
	fn via() -> Option<RelationDef> {
		Some(super::color::Relation::Board.def().rev())
	}
}

impl ActiveModelBehavior for ActiveModel {}
