//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "color")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub board: i32,
	#[sea_orm(primary_key, auto_increment = false)]
	pub index: i32,
	#[sea_orm(column_type = "Text")]
	pub name: String,
	pub value: i32,
	pub system_only: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::board::Entity",
		from = "Column::Board",
		to = "super::board::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Board,
	#[sea_orm(has_many = "super::placement::Entity")]
	Placement,
}

impl Related<super::board::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Board.def()
	}
}

impl Related<super::placement::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Placement.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
