//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2



use sea_orm :: entity :: prelude :: * ; use serde :: { Deserialize , Serialize } ;

# [derive (Clone , Debug , PartialEq , DeriveEntityModel , Eq , Serialize , Deserialize)] # [sea_orm (table_name = "color")] pub struct Model { # [sea_orm (primary_key , auto_increment = false)] # [serde (skip_deserializing)] pub board : i32 , # [sea_orm (primary_key , auto_increment = false)] # [serde (skip_deserializing)] pub index : i32 , # [sea_orm (column_type = "Text")] pub name : String , pub value : i32 , }

# [derive (Copy , Clone , Debug , EnumIter , DeriveRelation)] pub enum Relation { # [sea_orm (belongs_to = "super::board::Entity" , from = "Column::Board" , to = "super::board::Column::Id" , on_update = "NoAction" , on_delete = "NoAction" ,)] Board , # [sea_orm (has_many = "super::placement::Entity")] Placement , }

impl Related < super :: board :: Entity > for Entity { fn to () -> RelationDef { Relation :: Board . def () } }

impl Related < super :: placement :: Entity > for Entity { fn to () -> RelationDef { Relation :: Placement . def () } }

impl ActiveModelBehavior for ActiveModel { }