//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "faction_member")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub faction: i32,
	#[sea_orm(primary_key, auto_increment = false)]
	pub member: i32,
	pub owner: bool,
	pub imposed: bool,
	pub invited: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::faction::Entity",
		from = "Column::Faction",
		to = "super::faction::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Faction,
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::Member",
		to = "super::user::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	User,
}

impl Related<super::faction::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Faction.def()
	}
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::User.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
