//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod board;
pub mod board_notice;
pub mod board_sector;
pub mod color;
pub mod notice;
pub mod placement;
pub mod report;
pub mod report_artifact;
pub mod user_id;
