//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub mod prelude;

pub mod ban;
pub mod board;
pub mod board_notice;
pub mod board_sector;
pub mod color;
pub mod faction;
pub mod faction_member;
pub mod notice;
pub mod placement;
pub mod report;
pub mod report_artifact;
pub mod role;
pub mod role_member;
pub mod user;
