//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "notice")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	pub title: String,
	pub content: String,
	pub created_at: i64,
	pub expires_at: Option<i64>,
	pub author: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
