//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "placement")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i64,
	pub board: i32,
	pub position: i64,
	pub color: i16,
	pub timestamp: i32,
	#[sea_orm(column_type = "Text")]
	pub user_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::board::Entity",
		from = "Column::Board",
		to = "super::board::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Board,
	#[sea_orm(
		belongs_to = "super::color::Entity",
		from = "(Column::Board, Column::Board, Column::Color, Column::Color)",
		to = "(super::color::Column::Board, super::color::Column::Index, super::color::Column::Index, super::color::Column::Board)",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Color,
}

impl Related<super::color::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Color.def()
	}
}

impl Related<super::board::Entity> for Entity {
	fn to() -> RelationDef {
		super::color::Relation::Board.def()
	}
	fn via() -> Option<RelationDef> {
		Some(super::color::Relation::Placement.def().rev())
	}
}

impl ActiveModelBehavior for ActiveModel {}
