//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub use super::ban::Entity as Ban;
pub use super::board::Entity as Board;
pub use super::board_notice::Entity as BoardNotice;
pub use super::board_sector::Entity as BoardSector;
pub use super::color::Entity as Color;
pub use super::faction::Entity as Faction;
pub use super::faction_member::Entity as FactionMember;
pub use super::notice::Entity as Notice;
pub use super::placement::Entity as Placement;
pub use super::report::Entity as Report;
pub use super::report_artifact::Entity as ReportArtifact;
pub use super::role::Entity as Role;
pub use super::role_member::Entity as RoleMember;
pub use super::user::Entity as User;
