//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::ban::Entity as Ban;
pub use super::board::Entity as Board;
pub use super::board_notice::Entity as BoardNotice;
pub use super::board_sector::Entity as BoardSector;
pub use super::color::Entity as Color;
pub use super::notice::Entity as Notice;
pub use super::placement::Entity as Placement;
pub use super::report::Entity as Report;
pub use super::report_artifact::Entity as ReportArtifact;
pub use super::user_id::Entity as UserId;
