//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "report_artifact")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub report: i32,
	pub revision: i32,
	#[sea_orm(primary_key, auto_increment = false)]
	pub timestamp: i64,
	#[sea_orm(primary_key, auto_increment = false)]
	pub uri: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::report::Entity",
		from = "(Column::Report, Column::Revision)",
		to = "(super::report::Column::Id, super::report::Column::Revision)",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Report,
}

impl Related<super::report::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Report.def()
	}
}

impl Related<super::user_id::Entity> for Entity {
	fn to() -> RelationDef {
		super::report::Relation::UserId.def()
	}
	fn via() -> Option<RelationDef> {
		Some(super::report::Relation::ReportArtifact.def().rev())
	}
}

impl ActiveModelBehavior for ActiveModel {}
