//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "role")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	#[sea_orm(unique)]
	pub name: String,
	pub icon: Option<String>,
	pub permissions: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::role_member::Entity")]
	RoleMember,
}

impl Related<super::role_member::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::RoleMember.def()
	}
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef {
		super::role_member::Relation::User.def()
	}
	fn via() -> Option<RelationDef> {
		Some(super::role_member::Relation::Role.def().rev())
	}
}

impl ActiveModelBehavior for ActiveModel {}
