//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "role_member")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub role: i32,
	#[sea_orm(primary_key, auto_increment = false)]
	pub member: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(
		belongs_to = "super::role::Entity",
		from = "Column::Role",
		to = "super::role::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	Role,
	#[sea_orm(
		belongs_to = "super::user::Entity",
		from = "Column::Member",
		to = "super::user::Column::Id",
		on_update = "NoAction",
		on_delete = "NoAction"
	)]
	User,
}

impl Related<super::role::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Role.def()
	}
}

impl Related<super::user::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::User.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
