//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub id: i32,
	#[sea_orm(unique)]
	pub subject: String,
	pub name: String,
	pub created_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
	#[sea_orm(has_many = "super::board_notice::Entity")]
	BoardNotice,
	#[sea_orm(has_many = "super::faction_member::Entity")]
	FactionMember,
	#[sea_orm(has_many = "super::notice::Entity")]
	Notice,
	#[sea_orm(has_many = "super::placement::Entity")]
	Placement,
	#[sea_orm(has_many = "super::report::Entity")]
	Report,
	#[sea_orm(has_many = "super::role_member::Entity")]
	RoleMember,
}

impl Related<super::board_notice::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::BoardNotice.def()
	}
}

impl Related<super::faction_member::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::FactionMember.def()
	}
}

impl Related<super::notice::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Notice.def()
	}
}

impl Related<super::placement::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Placement.def()
	}
}

impl Related<super::report::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Report.def()
	}
}

impl Related<super::role_member::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::RoleMember.def()
	}
}

impl Related<super::faction::Entity> for Entity {
	fn to() -> RelationDef {
		super::faction_member::Relation::Faction.def()
	}
	fn via() -> Option<RelationDef> {
		Some(super::faction_member::Relation::User.def().rev())
	}
}

impl Related<super::report_artifact::Entity> for Entity {
	fn to() -> RelationDef {
		super::report::Relation::ReportArtifact.def()
	}
	fn via() -> Option<RelationDef> {
		Some(super::report::Relation::User.def().rev())
	}
}

impl Related<super::role::Entity> for Entity {
	fn to() -> RelationDef {
		super::role_member::Relation::Role.def()
	}
	fn via() -> Option<RelationDef> {
		Some(super::role_member::Relation::User.def().rev())
	}
}

impl ActiveModelBehavior for ActiveModel {}
