use std::fmt;

use enumset::EnumSetType;
use serde::{Serialize, Serializer, Deserialize, de::Visitor};

#[derive(Debug, EnumSetType)]
pub enum Permission {
	Info,
	BoardsList,
	BoardsGet,
	BoardsPost,
	BoardsPatch,
	BoardsDelete,
	BoardsDataGet,
	BoardsDataPatch,
	BoardsUsers,
	BoardsPixelsList,
	BoardsPixelsGet,
	BoardsPixelsPost,
	BoardsPixelsPatch,
	BoardsPixelsUndo,
	BoardsPixelsOverrideCooldown,
	BoardsPixelsOverrideColor,
	BoardsPixelsOverrideMask,
	UsersList,
	UsersGet,
	UsersPatch,
	UsersDelete,
	UsersCurrentGet,
	UsersCurrentPatch,
	UsersCurrentDelete,
	UsersRolesGet,
	UsersRolesPost,
	UsersRolesDelete,
	UsersCurrentRolesGet,
	UsersCurrentRolesPost,
	UsersCurrentRolesDelete,
	RolesList,
	RolesGet,
	RolesPost,
	RolesPatch,
	RolesDelete,
	NoticesList,
	NoticesGet,
	NoticesPost,
	NoticesPatch,
	NoticesDelete,
	ReportsList,
	ReportsHistoryList,
	ReportsGet,
	ReportsPost,
	ReportsPatch,
	ReportsDelete,
	ReportsOwnedList,
	ReportsOwnedHistoryList,
	ReportsOwnedGet,
	ReportsOwnedPatch,
	ReportsOwnedDelete,
	FactionsList,
	FactionsGet,
	FactionsPost,
	FactionsPatch,
	FactionsDelete,
	FactionsMembersList,
	FactionsMembersGet,
	FactionsMembersCurrentGet,
	FactionsMembersPost,
	FactionsMembersPatch,
	FactionsMembersDelete,
	UsersStatsGet,
	UsersStatsList,
	UsersBansList,
	UsersBansGet,
	UsersBansPost,
	UsersBansPatch,
	UsersBansDelete,
	UsersCurrentBansList,
	UsersCurrentBansGet,
	UsersFactionsList,
	UsersCurrentFactionsList,
	BoardsEventsDataColors,
	BoardsEventsDataTimestamps,
	BoardsEventsDataInitial,
	BoardsEventsDataMask,
	BoardsEventsInfo,
	BoardsEventsCooldown,
	BoardsEventsNotices,
	BoardsEventsStatistics,
	EventsAccess,
	EventsBoards,
	EventsRoles,
	EventsUsersRoles,
	EventsUsersCurrentRoles,
	EventsUsers,
	EventsUsersCurrent,
	EventsNotices,
	EventsReports,
	EventsReportsOwned,
	EventsStatistics,
	EventsUsersBans,
	EventsUsersCurrentBans,
	EventsFactions,
	EventsFactionsCurrent,
	EventsFactionsMembers,
	EventsFactionsCurrentMembers,
}

impl Permission {
	pub fn to_current(self) -> Option<Self> {
		match self {
			Self::UsersGet => Some(Self::UsersCurrentGet),
			Self::UsersPatch => Some(Self::UsersCurrentPatch),
			Self::UsersDelete => Some(Self::UsersCurrentDelete),
			Self::UsersRolesGet => Some(Self::UsersCurrentRolesGet),
			Self::UsersRolesPost => Some(Self::UsersCurrentRolesPost),
			Self::UsersRolesDelete => Some(Self::UsersCurrentRolesDelete),
			Self::ReportsList => Some(Self::ReportsOwnedList),
			Self::ReportsHistoryList => Some(Self::ReportsOwnedHistoryList),
			Self::ReportsGet => Some(Self::ReportsOwnedGet),
			Self::ReportsPatch => Some(Self::ReportsOwnedPatch),
			Self::ReportsDelete => Some(Self::ReportsOwnedDelete),
			Self::UsersBansList => Some(Self::UsersCurrentBansList),
			Self::UsersBansGet => Some(Self::UsersCurrentBansGet),
			Self::UsersFactionsList => Some(Self::UsersCurrentFactionsList),
			Self::FactionsMembersGet => Some(Self::FactionsMembersCurrentGet),
			Self::EventsUsersRoles => Some(Self::EventsUsersCurrentRoles),
			Self::EventsUsers => Some(Self::EventsUsersCurrent),
			Self::EventsUsersBans => Some(Self::EventsUsersCurrentBans),
			Self::EventsFactions => Some(Self::EventsFactionsCurrent),
			Self::EventsFactionsMembers => Some(Self::EventsFactionsCurrentMembers),
			_ => None,
		}
	}
}

impl From<&Permission> for &str {
	fn from(permission: &Permission) -> Self {
		match permission {
			Permission::Info => "info",
			Permission::BoardsList => "boards.list",
			Permission::BoardsGet => "boards.get",
			Permission::BoardsPost => "boards.post",
			Permission::BoardsPatch => "boards.patch",
			Permission::BoardsDelete => "boards.delete",
			Permission::BoardsDataGet => "boards.data.get",
			Permission::BoardsDataPatch => "boards.data.patch",
			Permission::BoardsUsers => "boards.users",
			Permission::BoardsPixelsList => "boards.pixels.list",
			Permission::BoardsPixelsGet => "boards.pixels.get",
			Permission::BoardsPixelsPost => "boards.pixels.post",
			Permission::BoardsPixelsPatch => "boards.pixels.patch",
			Permission::BoardsPixelsUndo => "boards.pixels.undo",
			Permission::BoardsPixelsOverrideCooldown => "boards.pixels.override.cooldown",
			Permission::BoardsPixelsOverrideColor => "boards.pixels.override.color",
			Permission::BoardsPixelsOverrideMask => "boards.pixels.override.mask",
			Permission::UsersList => "users.list",
			Permission::UsersGet => "users.get",
			Permission::UsersPatch => "users.patch",
			Permission::UsersDelete => "users.delete",
			Permission::UsersCurrentGet => "users.current.get",
			Permission::UsersCurrentPatch => "users.current.patch",
			Permission::UsersCurrentDelete => "users.current.delete",
			Permission::UsersRolesGet => "users.roles.get",
			Permission::UsersRolesPost => "users.roles.post",
			Permission::UsersRolesDelete => "users.roles.delete",
			Permission::UsersCurrentRolesGet => "users.current.roles.get",
			Permission::UsersCurrentRolesPost => "users.current.roles.post",
			Permission::UsersCurrentRolesDelete => "users.current.roles.delete",
			Permission::RolesList => "roles.list",
			Permission::RolesGet => "roles.get",
			Permission::RolesPost => "roles.post",
			Permission::RolesPatch => "roles.patch",
			Permission::RolesDelete => "roles.delete",
			Permission::NoticesList => "notices.list",
			Permission::NoticesGet => "notices.get",
			Permission::NoticesPost => "notices.post",
			Permission::NoticesPatch => "notices.patch",
			Permission::NoticesDelete => "notices.delete",
			Permission::ReportsList => "reports.list",
			Permission::ReportsHistoryList => "reports.history.list",
			Permission::ReportsGet => "reports.get",
			Permission::ReportsPost => "reports.post",
			Permission::ReportsPatch => "reports.patch",
			Permission::ReportsDelete => "reports.delete",
			Permission::ReportsOwnedList => "reports.owned.list",
			Permission::ReportsOwnedHistoryList => "reports.owned.history.list",
			Permission::ReportsOwnedGet => "reports.owned.get",
			Permission::ReportsOwnedPatch => "reports.owned.patch",
			Permission::ReportsOwnedDelete => "reports.owned.delete",
			Permission::FactionsList => "factions.list",
			Permission::FactionsGet => "factions.get",
			Permission::FactionsPost => "factions.post",
			Permission::FactionsPatch => "factions.patch",
			Permission::FactionsDelete => "factions.delete",
			Permission::FactionsMembersList => "factions.members.list",
			Permission::FactionsMembersGet => "factions.members.get",
			Permission::FactionsMembersCurrentGet => "factions.members.current.get",
			Permission::FactionsMembersPost => "factions.members.post",
			Permission::FactionsMembersPatch => "factions.members.patch",
			Permission::FactionsMembersDelete => "factions.members.delete",
			Permission::UsersStatsList => "users.stats.list",
			Permission::UsersStatsGet => "users.stats.get",
			Permission::UsersBansList => "users.bans.list",
			Permission::UsersBansGet => "users.bans.get",
			Permission::UsersBansPost => "users.bans.post",
			Permission::UsersBansPatch => "users.bans.patch",
			Permission::UsersBansDelete => "users.bans.delete",
			Permission::UsersCurrentBansGet => "users.current.bans.get",
			Permission::UsersCurrentBansList => "users.current.bans.list",
			Permission::UsersFactionsList => "users.factions.list",
			Permission::UsersCurrentFactionsList => "users.current.factions.list",
			Permission::BoardsEventsDataColors => "boards.events.data.colors",
			Permission::BoardsEventsDataTimestamps => "boards.events.data.timestamps",
			Permission::BoardsEventsDataInitial => "boards.events.data.initial",
			Permission::BoardsEventsDataMask => "boards.events.data.mask",
			Permission::BoardsEventsInfo => "boards.events.info",
			Permission::BoardsEventsCooldown => "boards.events.cooldown",
			Permission::BoardsEventsNotices => "boards.events.notices",
			Permission::BoardsEventsStatistics => "boards.events.stats",
			Permission::EventsAccess => "events.access",
			Permission::EventsBoards => "events.boards",
			Permission::EventsRoles => "events.roles",
			Permission::EventsUsersRoles => "events.users.roles",
			Permission::EventsUsersCurrentRoles => "events.users.current.roles",
			Permission::EventsUsers => "events.users",
			Permission::EventsUsersCurrent => "events.users.current",
			Permission::EventsNotices => "events.notices",
			Permission::EventsReports => "events.reports",
			Permission::EventsReportsOwned => "events.reports.owned",
			Permission::EventsStatistics => "events.stats",
			Permission::EventsUsersBans => "events.users.bans",
			Permission::EventsUsersCurrentBans => "events.users.current.bans",
			Permission::EventsFactions => "events.factions",
			Permission::EventsFactionsCurrent => "events.factions.current",
			Permission::EventsFactionsMembers => "events.factions.members",
			Permission::EventsFactionsCurrentMembers => "events.factions.current.members",
		}
	}
}

impl TryFrom<&str> for Permission {
	type Error = ();

	fn try_from(value: &str) -> Result<Self, Self::Error> {
		// TODO: find an way to exhaustively match this
		// (might need a proc macro with custom FromStr rules)
		match value {
			"info" => Ok(Permission::Info),
			"boards.list" => Ok(Permission::BoardsList),
			"boards.get" => Ok(Permission::BoardsGet),
			"boards.post" => Ok(Permission::BoardsPost),
			"boards.patch" => Ok(Permission::BoardsPatch),
			"boards.delete" => Ok(Permission::BoardsDelete),
			"boards.data.get" => Ok(Permission::BoardsDataGet),
			"boards.data.patch" => Ok(Permission::BoardsDataPatch),
			"boards.users" => Ok(Permission::BoardsUsers),
			"boards.pixels.list" => Ok(Permission::BoardsPixelsList),
			"boards.pixels.get" => Ok(Permission::BoardsPixelsGet),
			"boards.pixels.post" => Ok(Permission::BoardsPixelsPost),
			"boards.pixels.patch" => Ok(Permission::BoardsPixelsPatch),
			"boards.pixels.undo" => Ok(Permission::BoardsPixelsUndo),
			"boards.pixels.override.cooldown" => Ok(Permission::BoardsPixelsOverrideCooldown),
			"boards.pixels.override.color" => Ok(Permission::BoardsPixelsOverrideColor),
			"boards.pixels.override.mask" => Ok(Permission::BoardsPixelsOverrideMask),
			"users.list" => Ok(Permission::UsersList),
			"users.get" => Ok(Permission::UsersGet),
			"users.patch" => Ok(Permission::UsersPatch),
			"users.delete" => Ok(Permission::UsersDelete),
			"users.current.get" => Ok(Permission::UsersCurrentGet),
			"users.current.patch" => Ok(Permission::UsersCurrentPatch),
			"users.current.delete" => Ok(Permission::UsersCurrentDelete),
			"users.roles.get" => Ok(Permission::UsersRolesGet),
			"users.roles.post" => Ok(Permission::UsersRolesPost),
			"users.roles.delete" => Ok(Permission::UsersRolesDelete),
			"users.current.roles.get" => Ok(Permission::UsersCurrentRolesGet),
			"users.current.roles.post" => Ok(Permission::UsersCurrentRolesPost),
			"users.current.roles.delete" => Ok(Permission::UsersCurrentRolesDelete),
			"roles.list" => Ok(Permission::UsersList),
			"roles.get" => Ok(Permission::RolesGet),
			"roles.post" => Ok(Permission::RolesPost),
			"roles.patch" => Ok(Permission::RolesPatch),
			"roles.delete" => Ok(Permission::RolesDelete),
			"notices.list" => Ok(Permission::NoticesList),
			"notices.get" => Ok(Permission::NoticesGet),
			"notices.post" => Ok(Permission::NoticesPost),
			"notices.patch" => Ok(Permission::NoticesPatch),
			"notices.delete" => Ok(Permission::NoticesDelete),
			"reports.list" => Ok(Permission::ReportsList),
			"reports.history.list" => Ok(Permission::ReportsHistoryList),
			"reports.get" => Ok(Permission::ReportsGet),
			"reports.post" => Ok(Permission::ReportsPost),
			"reports.patch" => Ok(Permission::ReportsPatch),
			"reports.delete" => Ok(Permission::ReportsDelete),
			"reports.owned.list" => Ok(Permission::ReportsOwnedList),
			"reports.owned.history.list" => Ok(Permission::ReportsOwnedHistoryList),
			"reports.owned.get" => Ok(Permission::ReportsOwnedGet),
			"reports.owned.patch" => Ok(Permission::ReportsOwnedPatch),
			"reports.owned.delete" => Ok(Permission::ReportsOwnedDelete),
			"factions.list" => Ok(Permission::FactionsList),
			"factions.get" => Ok(Permission::FactionsGet),
			"factions.post" => Ok(Permission::FactionsPost),
			"factions.patch" => Ok(Permission::FactionsPatch),
			"factions.delete" => Ok(Permission::FactionsDelete),
			"factions.members.list" => Ok(Permission::FactionsMembersList),
			"factions.members.get" => Ok(Permission::FactionsMembersGet),
			"factions.members.current.get" => Ok(Permission::FactionsMembersCurrentGet),
			"factions.members.post" => Ok(Permission::FactionsMembersPost),
			"factions.members.patch" => Ok(Permission::FactionsMembersPatch),
			"factions.members.delete" => Ok(Permission::FactionsMembersDelete),
			"users.stats.list" => Ok(Permission::UsersStatsList),
			"users.stats.get" => Ok(Permission::UsersStatsGet),
			"users.bans.list" => Ok(Permission::UsersBansList),
			"users.bans.get" => Ok(Permission::UsersBansGet),
			"users.bans.post" => Ok(Permission::UsersBansPost),
			"users.bans.patch" => Ok(Permission::UsersBansPatch),
			"users.bans.delete" => Ok(Permission::UsersBansDelete),
			"users.current.bans.get" => Ok(Permission::UsersCurrentBansGet),
			"users.current.bans.list" => Ok(Permission::UsersCurrentBansList),
			"users.factions.list" => Ok(Permission::UsersFactionsList),
			"users.current.factions.list" => Ok(Permission::UsersCurrentFactionsList),
			"boards.events.data.colors" => Ok(Permission::BoardsEventsDataColors),
			"boards.events.data.timestamps" => Ok(Permission::BoardsEventsDataTimestamps),
			"boards.events.data.initial" => Ok(Permission::BoardsEventsDataInitial),
			"boards.events.data.mask" => Ok(Permission::BoardsEventsDataMask),
			"boards.events.info" => Ok(Permission::BoardsEventsInfo),
			"boards.events.cooldown" => Ok(Permission::BoardsEventsCooldown),
			"boards.events.notices" => Ok(Permission::BoardsEventsNotices),
			"boards.events.stats" => Ok(Permission::BoardsEventsStatistics),
			"events.access" => Ok(Permission::EventsAccess),
			"events.boards" => Ok(Permission::EventsBoards),
			"events.roles" => Ok(Permission::EventsRoles),
			"events.users.roles" => Ok(Permission::EventsUsersRoles),
			"events.users.current.roles" => Ok(Permission::EventsUsersCurrentRoles),
			"events.users" => Ok(Permission::EventsUsers),
			"events.users.current" => Ok(Permission::EventsUsersCurrent),
			"events.notices" => Ok(Permission::EventsNotices),
			"events.reports" => Ok(Permission::EventsReports),
			"events.reports.owned" => Ok(Permission::EventsReportsOwned),
			"events.stats" => Ok(Permission::EventsStatistics),
			"events.users.bans" => Ok(Permission::EventsUsersBans),
			"events.users.current.bans" => Ok(Permission::EventsUsersCurrentBans),
			"events.factions" => Ok(Permission::EventsFactions),
			"events.factions.current" => Ok(Permission::EventsFactionsCurrent),
			"events.factions.members" => Ok(Permission::EventsFactionsMembers),
			"events.factions.current.members" => Ok(Permission::EventsFactionsCurrentMembers),
			_ => Err(()),
		}
	}
}

impl Serialize for Permission {
	fn serialize<S: Serializer>(
		&self,
		serializer: S,
	) -> Result<S::Ok, S::Error> {
		serializer.serialize_str(self.into())
	}
}


struct V {}

impl<'de> Visitor<'de> for V {
	type Value = Permission;

	fn expecting(&self, formatter: &mut fmt::Formatter) -> fmt::Result {
		formatter.write_str("A permission string")
	}

	fn visit_str<E>(self, v: &str) -> Result<Self::Value, E>
	where E: serde::de::Error {
		Permission::try_from(v)
			.map_err(|_| E::custom("Invalid permission"))
	}
}

impl<'de> Deserialize<'de> for Permission {
	fn deserialize<D>(
		deserializer: D,
	) -> Result<Self, D::Error>
	where D: serde::Deserializer<'de> {
		deserializer.deserialize_str(V {})
	}
}
